version: "3.8"
services:
  db:
    container_name: kicks_db
    image: postgres:alpine3.17
    ports:
      - "8083:5432"
    environment:
      POSTGRES_USER: falcon_api_boilerplate
      POSTGRES_PASSWORD: falcon_api_boilerplate
      POSTGRES_DB: falcon_api_boilerplate
    restart: unless-stopped
  backend:
    container_name: kicks_api
    build: .
    image: kicks/backend:0.2.0
    volumes:
      - ./:/svc
    ports:
      - "8041:8000"
    depends_on:
      - db
    links:
      - db
  nginx:
    build:
      context: ./nginx
      args:
        DOMAIN: core-prd.errorinvest.com
        EMAIL: mail@ouafi.net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - db