---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    class: coloredlogs.ColoredFormatter
    format: "%(asctime)s - %(levelname)8s - %(message)s"
  json:
    format: "%(asctime)s - %(levelname)8s - %(message)s"
    class: "pythonjsonlogger.jsonlogger.JsonFormatter"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  falcon_api_boilerplate:
    level: DEBUG
    handlers: [console]
    propagate: no

  root:
    level: INFO
    handlers: [console]
