"""t

Revision ID: 5cda7ed616fc
Revises: a0b97a70216f
Create Date: 2023-04-23 14:30:03.987098

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5cda7ed616fc'
down_revision = 'a0b97a70216f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'size',
                    existing_type=sa.INTEGER(),
                    type_=sa.Numeric())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item', 'size',
                    existing_type=sa.Numeric(),
                    type_=sa.Integer())
    # ### end Alembic commands ###
