# -*- coding: utf-8 -*-

"""add currency model

Revision ID: a0b97a70216f
Revises: 4a4774a2a46b
Create Date: 2023-04-23 02:00:08.515335

"""
from alembic import op
import sqlalchemy as sa
from pathlib import Path


# revision identifiers, used by Alembic.
revision = 'a0b97a70216f'
down_revision = '4a4774a2a46b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('symbol', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.add_column('country', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'country', 'currency', ['currency_id'], ['id'])
    op.add_column('item', sa.Column('currency_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'currency', ['currency_id'], ['id'])
    op.drop_column('item', 'currency')
    # ### end Alembic commands ###

    with open(str(Path(__file__).with_suffix('')) + '_up.sql', 'r', encoding='utf-8') as f:
        op.execute(f.read())


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'currency_id')
    op.drop_constraint(None, 'country', type_='foreignkey')
    op.drop_column('country', 'currency_id')
    op.drop_table('currency')
    # ### end Alembic commands ###